Repository CUCyber/cuctf.io, pull requests merged in 2020-05, with the labels that each got.

#12 Implement Changes Recommended for #11
  .gitignore
  CNAME
  _config.yml
  _includes/navigation.html
  _layouts/default.html
  about.html
  contact.html
  index.html
  public/.DS_Store
  public/css/custom.css
  public/css/materialize.css
  public/css/materialize.min.css
  public/images/cu_shield.png
  public/images/favicon.ico
  public/images/shield-small.png
  public/images/shield.svg
  public/js/materialize.js
  public/js/materialize.min.js
  register.html
  team.html
Labels: bug, enhancement

#13 CUCTF Renovations
  _includes/navigation.html
  _layouts/default.html
  about.html
  cuctf_2019.html
  public/css/custom.css
  public/images/2019/Clemson_Team.png
  public/images/2019/GT_Team_A.png
  public/images/2019/GT_Team_B.png
  public/images/2019/Trophies.png
  public/images/Clemson_WattCenter.jpg
  public/images/TheBois.jpg
  winners.html
Labels: enhancement

#16 FAQs Update
  faqs.html
Labels: bug

#14 Implement Team Pictures and Bios
  _layouts/default.html
  public/css/custom.css
  public/images/profiles/charles.jpg
  public/images/profiles/david.jpg
  public/images/profiles/foster.jpg
  public/images/profiles/jacob.jpg
  public/images/profiles/kaitlyn.jpg
  public/images/profiles/maddie.jpg
  public/images/profiles/matthew_e.jpg
  public/images/profiles/matthew_r.jpg
  public/images/profiles/nick.jpg
  public/images/profiles/sean.jpg
  public/images/profiles/stick.png
  team.html
Labels: bug, help wanted
