Repository CUCyber/cuctf.io, pull requests merged in 2020-04, with the labels that each got.

#1 First Commit
  FAQ.html
  _includes/navigation.html
  _layouts/default.html
  about.html
  images/ally-logo.jpg
  images/crowdstrike-logo.png
  images/fireeye-logo.jpg
  images/secureworks-logo.jpg
  images/secureworks-tlogo.jpg
  images/secureworks-tlogo.png
  images/specterops-logo.jpg
  images/specterops-tlogo.jpg
  images/specterops-tlogo.png
  index.html
  register.html
  sponsor.html
  styles/LICENSE
  styles/bootstrap.css
  styles/bootstrap.min.css
  styles/bower.json
  styles/material.css
  styles/material.js
  styles/material.min.css
  styles/material.min.css.map
  styles/material.min.js
  styles/material.min.js.map
  styles/originalbootstrapdarkly.css
  styles/package.json
  styles/sticky-footer.css
  uploads/CUCTF_Sponsorship.pdf
  uploads/CUCTF_schedule.pdf
  winners.html
Labels: bug, enhancement

#8 Clean up html pages
  FAQ.html
  _includes/navigation.html
  _layouts/default.html
  about.html
  images/shieldNoText.svg
  index.html
  register.html
  sponsor.html
  styles/customizations.css
Labels: bug, enhancement

#6 Add a jekyll config file
  .gitignore
  _config.yml
Labels: enhancement

#5 Embed registration form into register.html
  register.html
  styles/customizations.css
Labels: enhancement

#7 Fix tab bar icon not loading
  _layouts/default.html
Labels: bug
